### ISSUE TITLE
Number is parsed as name for Search command 

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#102]
`search 1`
When getName() -> 1

**Comment by LingJie-Zhu** [comment]
Parsing takes in numbers as both ID and name. To check on SearchCommandRunner.

**Comment by tsoonjin** [comment]
@LingJie-Zhu  It is ok to parse in number as name, but can you parse tag without "#" so that I do not need to filter them when I do my comparison.
