### ISSUE TITLE
Set up a working parser  

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#26]
Parser wll return Command which will be executed by CommandRunner

**Comment by LingJie-Zhu** [comment]
How to escape certain keywords, come up with a list of delimiters. 
No unix commands and styles for the input (-t)

**Comment by LingJie-Zhu** [comment]
Detect: by, followed by a date format
Another good way? Put movie titles under quotes? Test first!

**Comment by tsoonjin** [comment]
Using regex is a good choice coupled with suitable data structure. Can refer to [Writing parser the tokenizer](http://cogitolearning.co.uk/?p=525)
