### ISSUE TITLE
add flexible task for task without specific deadline 

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#3]
so that users can use the To-Do task managers for tasks that are not urgent. These type of tasks can be recorded down on the program without users having to remember them.

**Comment by LingJie-Zhu** [comment]
Happens for tasks like "add something". Currently not implemented.
- From V0.1,
  Currently when parsing, a null DateTime object is passed in as there is no date specified. 
  When display is executed, a NullPointerException happens.
