### ISSUE TITLE
Project Manual V0.1 

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#46]
Things to be completed includes: 
# Requirements
- 10 pages 
- single pdf file 
# User guide
- Refining user guide by including explanation of terminnologies and meaning of flags
- Include small UI prototype in the user guide 
- Give credits to third party material: Gson
# Developer guide
- architecture 
- important APIs of each component ( logic, ui, storage, common )
- design description ( class diagram, sequence diagram, thoughts behind decision )
- instructions on how to test and run

**Comment by LingJie-Zhu** [comment]
Due on 12 October 2359 hrs.

**Comment by LingJie-Zhu** [comment]
Demo on 7 October tutorial.
