### ISSUE TITLE
Improve on parsing capabilities

### ISSUE THREAD

**Issue by LingJie-Zhu** [cs2103aug2015-w15-3j/main#52]
Either try to make use of natty date parser, or add in new recognition like the following:
- next Monday
- 2 hours later
- 2 weeks later

Which will be very time-consuming. Making use of natty would require the extraction of the date and time, which I need help in.

**Comment by LingJie-Zhu** [comment]
Add more time recognitions:
- 8pm 12am
- Today, Tomorrow

**Comment by LingJie-Zhu** [comment]
Alternative words for commands? 
Making use of -s and -e to signify start/end time period? (As well as -t for tags) Or introduce more delimiters such as commas, etc.

**Comment by LingJie-Zhu** [comment]
Consider breaking parser into smaller classes that focus on the smaller components of parsing. (Date, time, etc)

**Comment by tsoonjin** [comment]
I don't think we should add -s or -e to signify the start of date and end of date. What we have now is more powerful provided the parser can parse statement such as:

"add buy lightsaber from McDonald on my house by 19/9 1000 to 1200"

**Comment by leeyjj** [comment]
Users tag using '#' instead of '-t'

**Comment by LingJie-Zhu** [comment]
Added the following formats:
- < name > by  < start date > to < end date >
- < name > by < start time > to < end time >

**Comment by LingJie-Zhu** [comment]
EDIT will be making use of ADD. Therefore, edit format will follow that of ADD. 
- Example: "Edit 1 from 1800 to 2000" will change task 1's date to current date as it follows ADD convention.

**Comment by LingJie-Zhu** [comment]
Using "!" for priority delimiter, "#" for tag delimiter

**Comment by LingJie-Zhu** [comment]
For next iteration: Better DateTime recognitions. #94
