### ISSUE TITLE
Display overdue tasks 

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#66]
Show overdue tasks in default view

**Comment by leeyjj** [comment]
@LingJie-Zhu did we talk about an extra display option like "display overdue" or "display o"?

**Comment by LingJie-Zhu** [comment]
@jinified Don't think so, but we can include!

**Comment by tsoonjin** [comment]
Besides having the extra option to display overdue, overdue tasks are supposed to appear in the default view.

**Comment by leeyjj** [comment]
@LingJie-Zhu let's make "display o" then!
@jinified okay!
