### ISSUE TITLE
Add sidebar with additional details when application is maximised 

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#69]
# Sidebar includes:
- today (no of tasks)
- tomorrow (no of tasks) 
- next week (no of tasks) 
- projects (no of tasks | no of overdue tasks) 
- completed tasks (no of tasks)

**Comment by woanchin** [comment]
completed this first version. going to implement a detect enter key function for each button.

**Comment by woanchin** [comment]
enter has been completed, still considering whether to change buttons into a list.

-to do: I need to reflect the number of tasks done on the text of the buttons/list
