### ISSUE TITLE
Simple and Advanced Mode 

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#70]
When stage is minimized, `display only input bar and display bar`
When stage is maximised, `show sidebars`

**Comment by woanchin** [comment]
completed halfway, 

sidebars only show after program is shrunk to less than 750 width and then expanded more than 750. 

sidebars does not show if program is immediately expanded to more than 750.

**Comment by tsoonjin** [comment]
Instead of checking for width, a more consistent way is to check for minimized and maximized state in JavaFX. We will have a shortcut to minimize and maximize the window.
