### ISSUE TITLE
Batch command for Add

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#71]
- Add `multiple tasks` with same details 
- Delete multiple tasks ID, tags
- Done multipe tasks ID, tags

**Comment by LingJie-Zhu** [comment]
For adding multiple tasks, what format would be acceptable?
- addm task1 < delimiter > task2 < delimiter > task3 on < datetime format >

Examples of delimiters:
- &&
- ...
- //
- etc

**Comment by LingJie-Zhu** [comment]
Batch done and delete commands completed:
- "done 1 school 2 work 3":Mark as done tasks 1, 2, 3 and tags "school" and "work".
- "delete 1 2 3 school work": Deletes tasks 1, 2, 3 and tags "school" and "work".

**Comment by tsoonjin** [comment]
Refer to issue #92 for done and delete batch command
