### ISSUE TITLE
Parsing Extra Features

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#79]
## Ability to parse the following:
- task id of parent (subtask)
- priority 
- project ( -p ) 
  > a project contains multiple tasks that can contain multiple subtasks

**Comment by tsoonjin** [comment]
@LingJie-Zhu remember to support "set" command to switch directory

**Comment by LingJie-Zhu** [comment]
Where shall we include the project information in the ParsedInput object?

**Comment by LingJie-Zhu** [comment]
Project to be done on next milestone. #93
