### ISSUE TITLE
feedback bar should limit task name's length for full feedback to be displayed successfully

### ISSUE THREAD

**Issue by leeyjj** [cs2103aug2015-w15-3j/main#86]
e.g. when adding or deleting tasks with super long names (>50 charas) the feedback bar cannot display the full success message (refer to attached pic)

![raijinstatus](https://cloud.githubusercontent.com/assets/12386952/10557654/56fb5a06-74e7-11e5-9c20-332b49aaa8a3.jpg)

**Comment by tsoonjin** [comment]
I will set a limit on status class so that messages from all components won't have this problem
