### ISSUE TITLE
parser doesn't catch invalid inputs like "add" "delete" that has no more arguments

### ISSUE THREAD

**Issue by leeyjj** [cs2103aug2015-w15-3j/main#87]
e.g. when user simply types in "add", "edit" or "add " (with a space only) etc, console returns nullpointerexception instead of raijin throwing an illegalcommandargument.

**Comment by tsoonjin** [comment]
I will check on this. Perhaps related thing i added

**Comment by LingJie-Zhu** [comment]
Fixed this. Problem was with my parsing. Haven't check through system testing yet.

**Comment by tsoonjin** [comment]
Just checked and everything is working fine now
