### ISSUE TITLE
When the window is minimized the display view should scale accordingly  

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#89]

**Comment by leeyjj** [comment]
@jinified can we set it such that there's a limit for resizing the window to be smaller? If the window is allowed to scale indefinitely (e.g. to a width of 50px) there isn't any space for the details to be displayed properly.

**Comment by tsoonjin** [comment]
@woanchin  i agree just set a limit of resizing for the main application
