### ISSUE TITLE
editing the date for a task with high priority sets the priority to medium

### ISSUE THREAD

**Issue by leeyjj** [cs2103aug2015-w15-3j/main#90]

**Comment by leeyjj** [comment]
same for low priority, it got set to medium.

**Comment by tsoonjin** [comment]
@LingJie-Zhu you can parse priority already ? If it is set confirmed will be changed

**Comment by leeyjj** [comment]
editing the priority also reset the tags to no tags. editing tags also reset priority to mid

**Comment by tsoonjin** [comment]
U mean using edit command runner ? @LingJie-Zhu  can you take a look at it

**Comment by LingJie-Zhu** [comment]
@jinified yes I think the problem lies in EditCommandRunner. Will look into it

**Comment by LingJie-Zhu** [comment]
Edit supports the following after fixes:
- Name
- DateTime
- Priority
- Tags (Replaces all current tags associated)
