### ISSUE TITLE
Adjust Delete/DoneCommandRunners to support batch delete/done commands accordingly.

### ISSUE THREAD

**Issue by LingJie-Zhu** [cs2103aug2015-w15-3j/main#92]
Parsing has been made to accept multiple ID inputs already.

**Comment by LingJie-Zhu** [comment]
Need help on delete/done commands using tag... Are we doing it?

**Comment by tsoonjin** [comment]
Yes

**Comment by tsoonjin** [comment]
@LingJie-Zhu  your parsed tag should not include "#". Can fix that.

**Comment by tsoonjin** [comment]
Batch delete and done now works with multiple IDs
