### ISSUE TITLE
delete <random string> returns a success feedback

### ISSUE THREAD

**Issue by leeyjj** [cs2103aug2015-w15-3j/main#97]
i.e. "delete xxx", "delete somerubbish" will return a success feedback of "You have just deleted null!" and nothing was deleted. This command was added to undo stack as well.

**Comment by tsoonjin** [comment]
ok will check on my side

**Comment by LingJie-Zhu** [comment]
delete supports tags also, probably the checking of existing tags has problems?

**Comment by tsoonjin** [comment]
It is because you never check when id is empty or not. Fixed already by doing a check after retrieving id from tag.
